// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bol.proto

package bolproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Price struct {
	Price                float32  `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a3777cdcc5f749, []int{0}
}

func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Price) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type PriceEvaluationRequest struct {
	CurrentPrice         *Price   `protobuf:"bytes,1,opt,name=currentPrice,proto3" json:"currentPrice,omitempty"`
	HistoricalPrices     []*Price `protobuf:"bytes,2,rep,name=historicalPrices,proto3" json:"historicalPrices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceEvaluationRequest) Reset()         { *m = PriceEvaluationRequest{} }
func (m *PriceEvaluationRequest) String() string { return proto.CompactTextString(m) }
func (*PriceEvaluationRequest) ProtoMessage()    {}
func (*PriceEvaluationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a3777cdcc5f749, []int{1}
}

func (m *PriceEvaluationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceEvaluationRequest.Unmarshal(m, b)
}
func (m *PriceEvaluationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceEvaluationRequest.Marshal(b, m, deterministic)
}
func (m *PriceEvaluationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceEvaluationRequest.Merge(m, src)
}
func (m *PriceEvaluationRequest) XXX_Size() int {
	return xxx_messageInfo_PriceEvaluationRequest.Size(m)
}
func (m *PriceEvaluationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceEvaluationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PriceEvaluationRequest proto.InternalMessageInfo

func (m *PriceEvaluationRequest) GetCurrentPrice() *Price {
	if m != nil {
		return m.CurrentPrice
	}
	return nil
}

func (m *PriceEvaluationRequest) GetHistoricalPrices() []*Price {
	if m != nil {
		return m.HistoricalPrices
	}
	return nil
}

type PriceEvaluationResponse struct {
	Action               string   `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceEvaluationResponse) Reset()         { *m = PriceEvaluationResponse{} }
func (m *PriceEvaluationResponse) String() string { return proto.CompactTextString(m) }
func (*PriceEvaluationResponse) ProtoMessage()    {}
func (*PriceEvaluationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52a3777cdcc5f749, []int{2}
}

func (m *PriceEvaluationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceEvaluationResponse.Unmarshal(m, b)
}
func (m *PriceEvaluationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceEvaluationResponse.Marshal(b, m, deterministic)
}
func (m *PriceEvaluationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceEvaluationResponse.Merge(m, src)
}
func (m *PriceEvaluationResponse) XXX_Size() int {
	return xxx_messageInfo_PriceEvaluationResponse.Size(m)
}
func (m *PriceEvaluationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceEvaluationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PriceEvaluationResponse proto.InternalMessageInfo

func (m *PriceEvaluationResponse) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func init() {
	proto.RegisterType((*Price)(nil), "bolproto.Price")
	proto.RegisterType((*PriceEvaluationRequest)(nil), "bolproto.PriceEvaluationRequest")
	proto.RegisterType((*PriceEvaluationResponse)(nil), "bolproto.PriceEvaluationResponse")
}

func init() { proto.RegisterFile("bol.proto", fileDescriptor_52a3777cdcc5f749) }

var fileDescriptor_52a3777cdcc5f749 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0x4f, 0x4b, 0xc4, 0x30,
	0x14, 0xc4, 0x4d, 0x97, 0x5d, 0xec, 0xf3, 0x2f, 0x41, 0xd6, 0x22, 0x1e, 0x62, 0x4e, 0x7b, 0x2a,
	0xb8, 0x3d, 0xf6, 0xec, 0xbd, 0xe4, 0xe0, 0x3d, 0x0d, 0x81, 0x06, 0xd2, 0xbe, 0x98, 0xa4, 0x7e,
	0x08, 0x3f, 0xb5, 0x34, 0xad, 0x7f, 0x2b, 0xde, 0xde, 0x0c, 0xbf, 0xc9, 0x4c, 0x20, 0x6f, 0xd1,
	0x96, 0xce, 0x63, 0x44, 0x7a, 0xda, 0xa2, 0x4d, 0x17, 0xaf, 0x61, 0xdb, 0x78, 0xa3, 0x34, 0xbd,
	0x81, 0xad, 0x9b, 0x8e, 0x82, 0x30, 0x72, 0xc8, 0xc4, 0x2c, 0xe8, 0x3d, 0xe4, 0xd1, 0xf4, 0x3a,
	0x44, 0xd9, 0xbb, 0x22, 0x63, 0xe4, 0xb0, 0x11, 0x5f, 0x06, 0x7f, 0x23, 0xb0, 0x4f, 0xe9, 0xa7,
	0x57, 0x69, 0x47, 0x19, 0x0d, 0x0e, 0x42, 0xbf, 0x8c, 0x3a, 0x44, 0x5a, 0xc1, 0xb9, 0x1a, 0xbd,
	0xd7, 0x43, 0x6c, 0x3e, 0x5f, 0x3d, 0x3b, 0x5e, 0x95, 0x1f, 0xc5, 0x65, 0xb2, 0xc5, 0x0f, 0x88,
	0xd6, 0x70, 0xdd, 0x99, 0x10, 0xd1, 0x1b, 0x25, 0x6d, 0xb2, 0x42, 0x91, 0xb1, 0xcd, 0x5f, 0xc1,
	0x15, 0xc8, 0x1f, 0xe1, 0x76, 0xb5, 0x25, 0x38, 0x1c, 0x82, 0xa6, 0x7b, 0xd8, 0x49, 0x35, 0x39,
	0x69, 0x46, 0x2e, 0x16, 0x75, 0xec, 0xe0, 0xf2, 0x7b, 0x04, 0x3d, 0x7d, 0x86, 0x8b, 0x45, 0xe8,
	0x79, 0x12, 0xfb, 0x55, 0xbc, 0xfa, 0xe9, 0xdd, 0xc3, 0x3f, 0xc4, 0xdc, 0xcf, 0x4f, 0xda, 0x5d,
	0x02, 0xaa, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x80, 0xa6, 0x8f, 0xd5, 0x84, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PriceEvaluatorClient is the client API for PriceEvaluator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PriceEvaluatorClient interface {
	EvaluatePrice(ctx context.Context, in *PriceEvaluationRequest, opts ...grpc.CallOption) (*PriceEvaluationResponse, error)
}

type priceEvaluatorClient struct {
	cc *grpc.ClientConn
}

func NewPriceEvaluatorClient(cc *grpc.ClientConn) PriceEvaluatorClient {
	return &priceEvaluatorClient{cc}
}

func (c *priceEvaluatorClient) EvaluatePrice(ctx context.Context, in *PriceEvaluationRequest, opts ...grpc.CallOption) (*PriceEvaluationResponse, error) {
	out := new(PriceEvaluationResponse)
	err := c.cc.Invoke(ctx, "/bolproto.PriceEvaluator/EvaluatePrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PriceEvaluatorServer is the server API for PriceEvaluator service.
type PriceEvaluatorServer interface {
	EvaluatePrice(context.Context, *PriceEvaluationRequest) (*PriceEvaluationResponse, error)
}

// UnimplementedPriceEvaluatorServer can be embedded to have forward compatible implementations.
type UnimplementedPriceEvaluatorServer struct {
}

func (*UnimplementedPriceEvaluatorServer) EvaluatePrice(ctx context.Context, req *PriceEvaluationRequest) (*PriceEvaluationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluatePrice not implemented")
}

func RegisterPriceEvaluatorServer(s *grpc.Server, srv PriceEvaluatorServer) {
	s.RegisterService(&_PriceEvaluator_serviceDesc, srv)
}

func _PriceEvaluator_EvaluatePrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceEvaluationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceEvaluatorServer).EvaluatePrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bolproto.PriceEvaluator/EvaluatePrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceEvaluatorServer).EvaluatePrice(ctx, req.(*PriceEvaluationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PriceEvaluator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bolproto.PriceEvaluator",
	HandlerType: (*PriceEvaluatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluatePrice",
			Handler:    _PriceEvaluator_EvaluatePrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bol.proto",
}
